Repository MBTogether/MBT_Backend, pull requests merged in 2022-03, with the labels that each got.

#6 프로젝트 설정
  build.gradle
  src/main/java/com/example/mbtogether/domain/comment/entity/Comment.java
  src/main/java/com/example/mbtogether/domain/entity/User.java
  src/main/java/com/example/mbtogether/domain/exam/entity/MbtiExam.java
  src/main/java/com/example/mbtogether/domain/good/entity/Good.java
  src/main/java/com/example/mbtogether/domain/good/entity/GoodId.java
  src/main/java/com/example/mbtogether/domain/post/entity/Image.java
  src/main/java/com/example/mbtogether/domain/post/entity/Post.java
  src/main/java/com/example/mbtogether/domain/report/entity/CommentReport.java
  src/main/java/com/example/mbtogether/domain/report/entity/PostReport.java
  src/main/java/com/example/mbtogether/domain/repository/UserRepository.java
  src/main/java/com/example/mbtogether/domain/user/entity/User.java
  src/main/java/com/example/mbtogether/domain/user/repository/UserRepository.java
  src/main/java/com/example/mbtogether/global/config/JpaAuditingConfig.java
  src/main/java/com/example/mbtogether/global/dto/PagingResponse.java
  src/main/java/com/example/mbtogether/global/error/ErrorCode.java
  src/main/java/com/example/mbtogether/global/error/ErrorResponse.java
  src/main/java/com/example/mbtogether/global/error/Exception/CustomException.java
  src/main/java/com/example/mbtogether/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/mbtogether/global/security/AuthenticationFacade.java
  src/main/java/com/example/mbtogether/global/security/FilterConfigure.java
  src/main/java/com/example/mbtogether/global/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/mbtogether/global/security/SecurityConfig.java
  src/main/java/com/example/mbtogether/global/security/UserDetailService.java
  src/main/java/com/example/mbtogether/global/security/WebMvcConfig.java
  src/main/java/com/example/mbtogether/global/security/detail/AdminUserDetail.java
  src/main/java/com/example/mbtogether/global/security/detail/AuthUserDetail.java
  src/test/resources/application.yml
Labels: settings

#13 🌠 :: Feature/oauth
  src/main/java/com/example/mbtogether/domain/user/api/UserController.java
  src/main/java/com/example/mbtogether/domain/user/api/dto/request/RegisterRequest.java
  src/main/java/com/example/mbtogether/domain/user/api/dto/response/KakaoLinkResponse.java
  src/main/java/com/example/mbtogether/domain/user/api/dto/response/TokenResponse.java
  src/main/java/com/example/mbtogether/domain/user/repository/UserRepository.java
  src/main/java/com/example/mbtogether/domain/user/service/UserService.java
  src/main/java/com/example/mbtogether/infrastructure/client/KakaoAuth.java
  src/main/java/com/example/mbtogether/infrastructure/client/KakaoInfoClient.java
  src/main/java/com/example/mbtogether/infrastructure/dto/request/KakaoTokenRequest.java
  src/main/java/com/example/mbtogether/infrastructure/dto/response/KakaoInfoResponse.java
  src/main/java/com/example/mbtogether/infrastructure/dto/response/KakaoTokenResponse.java
  src/main/resources/application.yml
Labels: development

#17 ✅ :: contextLoads 오류 수정
  src/test/resources/application.yml
Labels: bug

#22 🌠 :: Feature/mbti exam
  src/main/java/com/example/mbtogether/domain/exam/api/MbtiExamController.java
  src/main/java/com/example/mbtogether/domain/exam/api/dto/request/MbtiExamRequest.java
  src/main/java/com/example/mbtogether/domain/exam/api/dto/response/MbtiExamResponse.java
  src/main/java/com/example/mbtogether/domain/exam/entity/MbtiExam.java
  src/main/java/com/example/mbtogether/domain/exam/exception/MbtiTypeNotFoundException.java
  src/main/java/com/example/mbtogether/domain/exam/repository/MbtiExamRepository.java
  src/main/java/com/example/mbtogether/domain/exam/service/MbtiExamService.java
  src/main/java/com/example/mbtogether/global/error/ErrorCode.java
  src/test/java/com/example/mbtogether/domain/exam/api/MbtiExamControllerTest.java
  src/test/java/com/example/mbtogether/domain/exam/service/MbtiExamServiceTest.java
Labels: development
